services:
  # Docker Registry
  registry:
    image: registry:2
    ports:
      - target: 5000
        published: 5001
        mode: host
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - registry-data:/var/lib/registry

  # Registry UI
  registry-ui:
    image: ghcr.io/vibhuvioio/docker-registry-ui:latest
    ports:
      - target: 5000
        published: 5000
        mode: host
    environment:
      LOG_LEVEL: INFO
      REGISTRIES: '[{"name":"Local Registry","api":"http://registry:5000"}]'
    volumes:
      - ui-data:/app/data

volumes:
  registry-data:
  ui-data:
