services:
  registry:
    image: registry:2
    container_name: docker-registry-dev
    ports:
      - "5001:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - registry-data:/var/lib/registry

  registry-ui:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    container_name: registry-ui-dev
    ports:
      - "8080:5000"
    environment:
      - CONFIG_FILE=/app/data/registries.config.json
      - READ_ONLY=false
    volumes:
      - ../app:/app/app
      - ../templates:/app/templates
      - ../static:/app/static
      - ../data:/app/data
    depends_on:
      - registry

volumes:
  registry-data:
